### ISSUE TITLE
JSONDecodeError still in API.py (t411api 0.1.3 with pip and python3.2)

### ISSUE THREAD

**Issue by julfur** [Xide/t411api#2]
Hi,

There is still a gap between github and pypi. Installing or upgrading from pypi still includes the JSONDecodeError import in API.py.

I upgraded **t411cli** from 0.5.0 to 0.5.5.
**t411api**, as a dependency, was upgraded too from 0.1.0 to 0.1.3.
`pip3 install -U t411cli`

Which results in:

```
pip3 freeze | grep t411
t411api==0.1.3
t411cli==0.5.5
```

Still having ImportError on JSONDecodeError.

```
cat /usr/local/lib/python3.2/dist-packages/t411api/API.py
"""
T411 API wrapper
May throw APIError -> (ConnectError, ServiceError)
"""

import os
import requests
from json import JSONDecodeError
```

The github repo looks good in 0.1.0 but pypi en 0.1.3 looks still broken.

Best regards.

**Comment by aslafy-z** [comment]
I just pushed new pypi version, working now ;)
