### ISSUE TITLE
server parameter

### ISSUE THREAD

**Issue by sinc59** [Xide/t411api#4]
Hello, 
the t411 domain is frequently changed.
Why do not expose the server parameter ?

Best regards

**Comment by aslafy-z** [comment]
Done, the API address can be specified to the T411API constructor:
```python
api = t411api.T411API(endpoint="https://my.awesome.api")
api.connect(...)
```

@Xide: can you release this to pypi ?

Implement it to https://github.com/Xide/t411cli is the next step.
